name: words625
version: '1.0.0+1'
publish_to: none
environment: 
  sdk: '>=3.2.3 <4.0.0'
description: Kannalinga - A Duolingo Alternative for Kannada Learning
dependencies: 
  animated_text_kit: '^4.2.2'
  audioplayers: any
  auto_route: 9.2.2
  chiclet: any
  contained_tab_bar_view: '^0.8.0'
  cupertino_icons: '^1.0.2'
  equatable: any
  flutter: 
    sdk: flutter
  flutter_animate: any
  flutter_custom_dialog: '^1.2.0'
  flutter_tts: any
  freezed: any
  get_it: any
  google_fonts: 6.0.0
  google_sign_in: any
  injectable: any
  json_annotation: any
  json_serializable: any
  logger: any
  percent_indicator: '^4.0.0'
  provider: any
  pulsator: any
  shimmer: any
  streaming_shared_preferences: any
dev_dependencies: 
  auto_route_generator: any
  build_runner: any
  flutter_animate: any
  flutter_gen: any
  flutter_gen_runner: any
  flutter_lints: '^2.0.0'
  flutter_test: 
    sdk: flutter
  import_sorter: any
  injectable_generator: any
  pubspec_dependency_sorter: any
  string_extension: any
flutter: 
  uses-material-design: true
  assets: 
    - assets/sounds/
    - assets/icons/
    - assets/images/
    - assets/screens/
